// <auto-generated />
using System;
using DelonLLC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DelonLLC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230622155232_first migrations")]
    partial class firstmigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DelonLLC.Dtos.CardRequestDto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("bank_name")
                        .HasColumnType("text");

                    b.Property<string>("card_description")
                        .HasColumnType("text");

                    b.Property<string>("card_holder")
                        .HasColumnType("text");

                    b.Property<string>("card_number")
                        .HasColumnType("text");

                    b.Property<string>("card_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("customer_id")
                        .HasColumnType("uuid");

                    b.Property<string>("expiry_date")
                        .HasColumnType("text");

                    b.Property<string>("mobile_network")
                        .HasColumnType("text");

                    b.Property<string>("mobile_number")
                        .HasColumnType("text");

                    b.Property<int?>("security_code")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("customer_cards");
                });
#pragma warning restore 612, 618
        }
    }
}
